-- Supabase table for video tutorials
-- Run this SQL in Supabase SQL editor

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  video_url text not null,
  created_at timestamptz default now()
);

-- Enable RLS
alter table if exists public.videos enable row level security;

-- Public read access for videos
create policy if not exists "Public can select videos" on public.videos
  for select
  using (true);

-- Admin full access for videos
create policy if not exists "Admin can manage videos" on public.videos
  for all
  using (auth.email() = 'admin@company.com')
  with check (auth.email() = 'admin@company.com');