\-- Supabase table for video tutorials

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  video_url text not null,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.videos enable row level security;

-- Public read access
create policy "Public can select videos"
on public.videos
for select
to public
using (true);

-- Authenticated users can manage videos
create policy "Admin can manage videos"
on public.videos
for all
to authenticated
using (
  auth.role() = 'authenticated'
)
with check (
  auth.role() = 'authenticated'
);
